### ISSUE TITLE
Better performing Tacview exporter?

### ISSUE THREAD

**Issue by shugamoe** [DCS-gRPC/rust-server#195]
I know there are certain DCS servers like Enigmas that don't use LotATC or Tacview server side for performance reasons, and I know that DCS-gRPC can help server performance by offloading expensive calculations. My initial thought is DCS-gRPC might not help improve server performance when used as the basis for unit position streaming/recording applications.

Presumably though, there are some expectations of improved performance with #131, so are there similar expectations if DCS-gRPC were used to create an alternate Tacview exporter?

**Comment by rurounijones** [comment]
There is nothing special about how DCS-gRPC does things that would make it any more efficient than Tacview or LotATC server in a direct comparison.

They all work the same way. Poll the server via lua to get unit information. This sucks and is not at all efficient but it is all that is available. There are some tricks that can be done to reduce per-frame impact (such as polling small groups at a time) which is, I believe, what Tacview does.

We are not aiming to replace Tacview. What we are aiming for, however, is for DCS-gRPC to be good enough, provide enough APIs, and be open-source so that people feel confident switching their back-ends to DCS-gRPC so that the number of plugins that are doing the lua polling is reduced. 

Currently a server running Tacview, DCS-gRPC and LotATC has three separate things doing that unit polling. If they all switched to DCS-gRPC then that reduces the load significantly.

Someone could definitely create a Tacview file writer based on the data that DCS-gRPC exports (It is already being done in the [LSO bot](https://github.com/DCS-gRPC/lso)) and it would bring the benefit of allowing tacview files to be created without needing Tacview on the server itself. But there is nothing special about how DCS-gRPC is doing things that make it inherently better.

**Comment by shugamoe** [comment]
Thank you so much for your detailed response and clearing up my understanding!
